### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by yaoqs**
(Creative Commons BY-SA 4.0) 知识共享署名 - 相同方式共享 4.0 国际许可协议

### CODE REVIEW

**Comment by DiamondI** [comment]
I noticed that this commit is from an unknown repository, according to github. May I know the purpose of this commit?

**Comment by yaoqs** [comment]
My purpose of this commit is to adding a license for this repository for people using it free and being avoid of copyright disputes.

**Comment by yaoqs** [comment]
The reason why this commit is from an unknown repository is that I delete my fork of this reposity inadvertently. it makes the repository show some abnormal. And in fact, it's just a warning.

**Comment by DiamondI** [comment]
OK, thanks for your contribution! 😃

**Pull request merged**
